# Generated by Django 4.1 on 2023-04-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firereport", "0006_firereport_assignedtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(max_length=200)),
                ("lon", models.FloatField(max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firereport.teams",
                    ),
                ),
            ],
        ),
    ]
