# Generated by Django 4.1 on 2023-04-06 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("firereport", "0007_teamlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamlocation",
            name="time_stamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
